### ISSUE TITLE
npm publish 

### ISSUE THREAD

**Issue by TLOWAC** [TLOWAC-REPO/config-toolkit#3]
### Todo
- [x] 단일 패키지 배포
     - [x] @TLOWAC/eslint-config
     - [x] @TLOWAC/prettier-config
- [ ] 패키지 배포 스크립트 작성

### Task Dependency
#1 
#2

**Comment by TLOWAC** [comment]
![image](https://user-images.githubusercontent.com/58043975/203714495-b7c0ed00-b6ca-43ef-815a-3534db82bdde.png)
