### ISSUE TITLE
snippet 제작

### ISSUE THREAD

**Issue by TLOWAC** [TLOWAC-REPO/config-toolkit#5]
## Todo
- [ ] eslint snippet 제작 ( `yarn add ...` , `eslintrrc`
- [ ] prettier snippet 제작
- [ ] stylelint snippet 제작
- [ ] README.md 업데이트
